import type {
  Application,
  CareerSuggestion,
  CvDoc,
  Job,
  MasterCv,
  Notification,
  Suggestion,
} from "./career-types";

export const emptyMasterCv: MasterCv = {
  name: "",
  title: "",
  email: "",
  phone: "",
  location: "",
  links: [],
  summary: "",
  experience: [],
  education: [],
  skills: [],
  languages: [],
  tools: [],
  certifications: [],
  projects: [],
  volunteer: [],
  updatedAt: new Date().toISOString(),
  template: "editorial",
  version: 1,
};

export const demoMasterCv: MasterCv = {
  name: "Amina Haddad",
  title: "Senior Product Designer",
  email: "amina.haddad@mail.com",
  phone: "+46 70 555 21 88",
  location: "Stockholm",
  links: ["linkedin.com/in/aminahaddad", "aminahaddad.design"],
  summary:
    "Product designer with 8 years across fintech and B2B SaaS. Leads end-to-end design for data-heavy products, from research to shipped interface, and works closely with engineering on design systems.",
  experience: [
    {
      id: "exp-1",
      role: "Senior Product Designer",
      company: "Northlane Fintech",
      location: "Stockholm",
      start: "2022-03",
      end: "Present",
      bullets: [
        "Led redesign of the payments dashboard used by 40,000 monthly business users.",
        "Built and maintained the shared design system with 3 engineers.",
        "Ran quarterly usability studies and turned findings into a prioritised roadmap.",
      ],
    },
    {
      id: "exp-2",
      role: "Product Designer",
      company: "Kartell Software",
      location: "Gothenburg",
      start: "2019-01",
      end: "2022-02",
      bullets: [
        "Designed onboarding for a B2B analytics product; activation improved from 31% to 48%.",
        "Introduced weekly design critiques across two product squads.",
      ],
    },
    {
      id: "exp-3",
      role: "UX Designer",
      company: "Studio Vela",
      location: "Malmö",
      start: "2017-06",
      end: "2018-12",
      bullets: [
        "Delivered interface work for 11 client projects in retail and public sector.",
        "Owned accessibility reviews before hand-off.",
      ],
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "Konstfack",
      program: "MFA, Interaction Design",
      start: "2015",
      end: "2017",
    },
    {
      id: "edu-2",
      school: "Lund University",
      program: "BSc, Cognitive Science",
      start: "2012",
      end: "2015",
    },
  ],
  skills: [
    "Product design",
    "Design systems",
    "User research",
    "Prototyping",
    "Interaction design",
    "Accessibility",
    "Workshop facilitation",
  ],
  languages: ["Swedish (native)", "English (fluent)", "Arabic (fluent)"],
  tools: ["Figma", "Framer", "Storybook", "Maze", "Linear", "Notion"],
  certifications: ["NN/g UX Certification (2021)"],
  projects: [
    {
      id: "prj-1",
      name: "Open Banking Patterns",
      description:
        "Public pattern library for consent and permission flows, used by three fintech teams.",
      year: "2023",
    },
  ],
  volunteer: ["Mentor at Design Sthlm Collective (2020–present)"],
  references: [
    {
      id: "ref-1",
      name: "Erik Lindqvist",
      relation: "Former design director",
      company: "Northlane Fintech",
      email: "erik.lindqvist@example.com",
      phone: "+46 70 123 45 67",
    },
  ],
  updatedAt: new Date().toISOString(),
  template: "editorial",
  version: 4,
};

export const demoCvDocs: CvDoc[] = [
  {
    id: "cv-master",
    name: "Master CV",
    kind: "master",
    updatedAt: "2 days ago",
    score: 78,
  },
  {
    id: "cv-1",
    name: "Klarna — Senior Product Designer",
    kind: "tailored",
    jobId: "job-1",
    updatedAt: "5 days ago",
    score: 86,
  },
  {
    id: "cv-2",
    name: "Spotify — Design Systems",
    kind: "tailored",
    jobId: "job-3",
    updatedAt: "2 weeks ago",
    score: 81,
  },
];

export const demoJobs: Job[] = [
  {
    id: "job-1",
    careerIds: ["career-3"],
    title: "Senior Product Designer",
    company: "Klarna",
    location: "Stockholm",
    mode: "Hybrid",
    posted: "2 days ago",
    source: "Company site",
    applyUrl: "https://www.klarna.com/careers/senior-product-designer",
    salary: "62 000 – 74 000 SEK / month",
    match: 88,
    matchingSkills: ["Design systems", "Fintech", "User research", "Figma"],
    gaps: ["Payments compliance", "Team leadership"],
    summary:
      "Own end-to-end design for merchant-facing payment tools in a cross-functional squad of designers, engineers and data scientists.",
    responsibilities: [
      "Drive the design direction for merchant onboarding and settlement flows.",
      "Partner with research to validate concepts with real merchants.",
      "Contribute components back to the central design system.",
      "Mentor two mid-level designers.",
    ],
    required: [
      "6+ years product design experience",
      "Portfolio with complex, data-heavy products",
      "Strong systems thinking",
      "Fluent English",
    ],
    preferred: ["Fintech or payments background", "Experience mentoring designers"],
    keywords: [
      "design system",
      "merchant",
      "payments",
      "end-to-end",
      "research",
      "accessibility",
      "cross-functional",
    ],
    experienceRequirement: "6+ years, senior individual contributor level",
  },
  {
    id: "job-2",
    careerIds: ["career-2", "career-3"],
    title: "Lead UX Designer",
    company: "Trustly",
    location: "Remote (EU)",
    mode: "Remote",
    posted: "5 days ago",
    source: "LinkedIn",
    applyUrl: "https://www.trustly.com/careers/lead-ux-designer",
    salary: "Not disclosed",
    match: 74,
    matchingSkills: ["Interaction design", "Prototyping", "Accessibility"],
    gaps: ["People management", "B2C scale"],
    summary:
      "Set UX direction for consumer payment journeys and lead a small distributed design team.",
    responsibilities: [
      "Define UX strategy for consumer flows across markets.",
      "Line-manage two designers.",
      "Establish research cadence.",
    ],
    required: ["7+ years UX experience", "Experience leading designers", "Consumer product background"],
    preferred: ["Multi-market localisation experience"],
    keywords: ["ux strategy", "leadership", "consumer", "payments", "research"],
    experienceRequirement: "7+ years with direct leadership experience",
  },
  {
    id: "job-3",
    careerIds: ["career-1"],
    title: "Design Systems Designer",
    company: "Spotify",
    location: "Stockholm",
    mode: "Hybrid",
    posted: "1 week ago",
    source: "Company site",
    applyUrl: "https://www.lifeatspotify.com/jobs/design-systems-designer",
    salary: "58 000 – 68 000 SEK / month",
    match: 81,
    matchingSkills: ["Design systems", "Storybook", "Accessibility", "Documentation"],
    gaps: ["Token tooling at scale"],
    summary:
      "Evolve the shared component library used by product teams across web and mobile surfaces.",
    responsibilities: [
      "Own component specs and documentation.",
      "Work with platform engineers on token pipelines.",
      "Run adoption sessions with product teams.",
    ],
    required: ["5+ years design experience", "Hands-on design system ownership"],
    preferred: ["Familiarity with design tokens and theming"],
    keywords: ["design system", "tokens", "components", "documentation", "adoption"],
    experienceRequirement: "5+ years, systems specialisation",
  },
  {
    id: "job-4",
    careerIds: ["career-1", "career-3"],
    title: "Product Designer, Platform",
    company: "Tink",
    location: "Stockholm",
    mode: "On-site",
    posted: "3 days ago",
    source: "Job board",
    applyUrl: "https://www.tink.com/careers/product-designer",
    match: 69,
    matchingSkills: ["Product design", "Prototyping"],
    gaps: ["Developer-tool design", "API documentation UX"],
    summary: "Design developer-facing tooling and dashboards for an open banking platform.",
    responsibilities: [
      "Design console experiences for developer customers.",
      "Improve API key and sandbox workflows.",
    ],
    required: ["4+ years product design", "Comfort with technical products"],
    preferred: ["Previous developer-tool experience"],
    keywords: ["developer experience", "api", "console", "platform"],
    experienceRequirement: "4+ years",
  },
];

export const demoApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    company: "Klarna",
    position: "Senior Product Designer",
    link: "https://klarna.com/careers/senior-product-designer",
    appliedDate: "2026-08-11",
    cvUsed: "Klarna — Senior Product Designer",
    status: "Interview",
    notes:
      "First call with hiring manager went well. They asked about design system governance and merchant research.",
    nextAction: "Portfolio deep-dive with the design team",
    nextActionDate: "2026-08-24",
    timeline: [
      { id: "ev-1", date: "2026-08-11", label: "Applied", detail: "Tailored CV v2 submitted" },
      { id: "ev-2", date: "2026-08-15", label: "Recruiter screen", detail: "30 min call" },
      { id: "ev-3", date: "2026-08-19", label: "Interview scheduled", detail: "Portfolio review" },
    ],
  },
  {
    id: "app-2",
    jobId: "job-3",
    company: "Spotify",
    position: "Design Systems Designer",
    link: "https://spotifyjobs.com/design-systems",
    appliedDate: "2026-08-06",
    cvUsed: "Spotify — Design Systems",
    status: "Applied",
    notes: "Referred by former colleague in the platform team.",
    nextAction: "Follow up if no response",
    nextActionDate: "2026-08-22",
    timeline: [{ id: "ev-4", date: "2026-08-06", label: "Applied", detail: "Tailored CV submitted" }],
  },
  {
    id: "app-3",
    jobId: "job-2",
    company: "Trustly",
    position: "Lead UX Designer",
    link: "https://trustly.com/careers",
    appliedDate: "2026-08-02",
    cvUsed: "Master CV",
    status: "Saved",
    notes: "Waiting to strengthen leadership evidence before applying.",
    timeline: [{ id: "ev-5", date: "2026-08-02", label: "Saved", detail: "From job discovery" }],
  },
  {
    id: "app-4",
    company: "Nordnet",
    position: "Product Designer",
    link: "https://nordnet.se/jobb",
    appliedDate: "2026-07-14",
    cvUsed: "Master CV",
    status: "Rejected",
    notes: "Position filled internally. Feedback: strong portfolio, timing issue.",
    timeline: [
      { id: "ev-6", date: "2026-07-14", label: "Applied" },
      { id: "ev-7", date: "2026-07-29", label: "Rejected", detail: "Role filled internally" },
    ],
  },
];

export const demoSuggestions: Suggestion[] = [
  {
    id: "sug-1",
    section: "Professional summary",
    issue: "Summary states scope but no outcome",
    severity: "high",
    rationale:
      "Recruiters scan the first two lines. Adding one measurable outcome makes the opening concrete without adding new claims.",
    before:
      "Product designer with 8 years across fintech and B2B SaaS. Leads end-to-end design for data-heavy products.",
    after:
      "Product designer with 8 years across fintech and B2B SaaS, leading end-to-end design for data-heavy products used by 40,000 monthly business users.",
    state: "pending",
  },
  {
    id: "sug-2",
    section: "Experience — Northlane Fintech",
    issue: "Achievement missing a measurable result",
    severity: "high",
    rationale:
      "The design system bullet describes activity, not effect. Rewritten using only facts already present elsewhere in your CV.",
    before: "Built and maintained the shared design system with 3 engineers.",
    after:
      "Built and maintained the shared design system with 3 engineers, standardising components across the payments dashboard.",
    state: "pending",
  },
  {
    id: "sug-3",
    section: "Experience — Studio Vela",
    issue: "Repetitive phrasing across bullets",
    severity: "medium",
    rationale: "Two bullets open with the same verb pattern, which weakens scanability.",
    before: "Owned accessibility reviews before hand-off.",
    after: "Ran accessibility reviews on every project before hand-off.",
    state: "pending",
  },
  {
    id: "sug-4",
    section: "Skills",
    issue: "Missing keywords relevant to your target roles",
    severity: "medium",
    rationale:
      "Three of your saved jobs mention these terms. Only add them if they genuinely reflect your experience.",
    before: "Product design, Design systems, User research…",
    after: "…plus: Cross-functional collaboration, Design documentation",
    state: "pending",
  },
  {
    id: "sug-5",
    section: "Formatting",
    issue: "Dates use mixed formats",
    severity: "low",
    rationale: "Consistent date formatting improves parsing by applicant tracking systems.",
    before: "2022-03 – Present / 2017 – 2018",
    after: "Mar 2022 – Present / Jun 2017 – Dec 2018",
    state: "pending",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "n-1",
    title: "Interview in 3 days",
    body: "Klarna portfolio deep-dive on 24 Aug. Review your tailored CV before the call.",
    time: "2h ago",
    kind: "application",
    read: false,
  },
  {
    id: "n-2",
    title: "4 new matched jobs",
    body: "Based on your Master CV, 4 roles above 70% match were published this week.",
    time: "Yesterday",
    kind: "job",
    read: false,
  },
  {
    id: "n-3",
    title: "5 CV recommendations ready",
    body: "The assistant reviewed your Master CV and found 2 high-priority improvements.",
    time: "2 days ago",
    kind: "ai",
    read: true,
  },
  {
    id: "n-4",
    title: "Follow-up due",
    body: "No reply from Spotify since 6 Aug. Consider a short follow-up message.",
    time: "3 days ago",
    kind: "application",
    read: true,
  },
];

export const statusOrder = [
  "Saved",
  "Applied",
  "Interview",
  "Second interview",
  "Offer",
  "Rejected",
  "Withdrawn",
  "Closed",
] as const;

export const demoCareerSuggestions: CareerSuggestion[] = [
  {
    id: "career-1",
    title: "Design Systems Lead",
    why: "You already build and maintain a shared component library with engineers — that is the core of this role.",
    transferable: ["Design systems", "Documentation", "Cross-team collaboration"],
    openings: 12,
    match: 84,
  },
  {
    id: "career-2",
    title: "UX Researcher",
    why: "Your CV shows repeated user research, interviews and usability testing across fintech products.",
    transferable: ["User research", "Interviews", "Usability testing"],
    openings: 9,
    match: 76,
  },
  {
    id: "career-3",
    title: "Product Manager, Platform",
    why: "You have owned end-to-end product decisions with measurable outcomes and worked closely with data.",
    transferable: ["Product discovery", "Stakeholder alignment", "Data-informed decisions"],
    openings: 15,
    match: 71,
  },
];
